# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.content.protocols_content_pb2 as protocols__content__pb2


class ContentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/contents_service_grpc.ContentService/CreatePost',
                request_serializer=protocols__content__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=protocols__content__pb2.PostId.FromString,
                )
        self.UpdatePost = channel.unary_unary(
                '/contents_service_grpc.ContentService/UpdatePost',
                request_serializer=protocols__content__pb2.UpdatePostRequest.SerializeToString,
                response_deserializer=protocols__content__pb2.StatusResponse.FromString,
                )
        self.DeletePost = channel.unary_unary(
                '/contents_service_grpc.ContentService/DeletePost',
                request_serializer=protocols__content__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=protocols__content__pb2.StatusResponse.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/contents_service_grpc.ContentService/GetPost',
                request_serializer=protocols__content__pb2.PostId.SerializeToString,
                response_deserializer=protocols__content__pb2.PostResponse.FromString,
                )
        self.GetPostsList = channel.unary_unary(
                '/contents_service_grpc.ContentService/GetPostsList',
                request_serializer=protocols__content__pb2.PostsListRequest.SerializeToString,
                response_deserializer=protocols__content__pb2.PostsListResponse.FromString,
                )


class ContentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=protocols__content__pb2.CreatePostRequest.FromString,
                    response_serializer=protocols__content__pb2.PostId.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=protocols__content__pb2.UpdatePostRequest.FromString,
                    response_serializer=protocols__content__pb2.StatusResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=protocols__content__pb2.DeletePostRequest.FromString,
                    response_serializer=protocols__content__pb2.StatusResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=protocols__content__pb2.PostId.FromString,
                    response_serializer=protocols__content__pb2.PostResponse.SerializeToString,
            ),
            'GetPostsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostsList,
                    request_deserializer=protocols__content__pb2.PostsListRequest.FromString,
                    response_serializer=protocols__content__pb2.PostsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contents_service_grpc.ContentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contents_service_grpc.ContentService/CreatePost',
            protocols__content__pb2.CreatePostRequest.SerializeToString,
            protocols__content__pb2.PostId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contents_service_grpc.ContentService/UpdatePost',
            protocols__content__pb2.UpdatePostRequest.SerializeToString,
            protocols__content__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contents_service_grpc.ContentService/DeletePost',
            protocols__content__pb2.DeletePostRequest.SerializeToString,
            protocols__content__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contents_service_grpc.ContentService/GetPost',
            protocols__content__pb2.PostId.SerializeToString,
            protocols__content__pb2.PostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPostsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/contents_service_grpc.ContentService/GetPostsList',
            protocols__content__pb2.PostsListRequest.SerializeToString,
            protocols__content__pb2.PostsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
