# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocols_content.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protocols_content.proto\x12\x15\x63ontents_service_grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n\x11\x43reatePostRequest\x12\x11\n\tauthor_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"J\n\x11UpdatePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07post_id\x18\x02 \x01(\x04\x12\x13\n\x0bnew_content\x18\x03 \x01(\t\"\x19\n\x06PostId\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\"!\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xa3\x01\n\x0cPostResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\x04\x12\x11\n\tauthor_id\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12+\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rlast_modified\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"H\n\x10PostsListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08page_num\x18\x02 \x01(\x04\x12\x11\n\tpage_size\x18\x03 \x01(\x04\"G\n\x11PostsListResponse\x12\x32\n\x05posts\x18\x01 \x03(\x0b\x32#.contents_service_grpc.PostResponse\"5\n\x11\x44\x65letePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0f\n\x07post_id\x18\x02 \x01(\x04\x32\xe1\x03\n\x0e\x43ontentService\x12W\n\nCreatePost\x12(.contents_service_grpc.CreatePostRequest\x1a\x1d.contents_service_grpc.PostId\"\x00\x12_\n\nUpdatePost\x12(.contents_service_grpc.UpdatePostRequest\x1a%.contents_service_grpc.StatusResponse\"\x00\x12_\n\nDeletePost\x12(.contents_service_grpc.DeletePostRequest\x1a%.contents_service_grpc.StatusResponse\"\x00\x12O\n\x07GetPost\x12\x1d.contents_service_grpc.PostId\x1a#.contents_service_grpc.PostResponse\"\x00\x12\x63\n\x0cGetPostsList\x12\'.contents_service_grpc.PostsListRequest\x1a(.contents_service_grpc.PostsListResponse\"\x00\x42\x1eZ\x1cproto/;contents_service_grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols_content_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\034proto/;contents_service_grpc'
  _globals['_CREATEPOSTREQUEST']._serialized_start=83
  _globals['_CREATEPOSTREQUEST']._serialized_end=138
  _globals['_UPDATEPOSTREQUEST']._serialized_start=140
  _globals['_UPDATEPOSTREQUEST']._serialized_end=214
  _globals['_POSTID']._serialized_start=216
  _globals['_POSTID']._serialized_end=241
  _globals['_STATUSRESPONSE']._serialized_start=243
  _globals['_STATUSRESPONSE']._serialized_end=276
  _globals['_POSTRESPONSE']._serialized_start=279
  _globals['_POSTRESPONSE']._serialized_end=442
  _globals['_POSTSLISTREQUEST']._serialized_start=444
  _globals['_POSTSLISTREQUEST']._serialized_end=516
  _globals['_POSTSLISTRESPONSE']._serialized_start=518
  _globals['_POSTSLISTRESPONSE']._serialized_end=589
  _globals['_DELETEPOSTREQUEST']._serialized_start=591
  _globals['_DELETEPOSTREQUEST']._serialized_end=644
  _globals['_CONTENTSERVICE']._serialized_start=647
  _globals['_CONTENTSERVICE']._serialized_end=1128
# @@protoc_insertion_point(module_scope)
