openapi: '3.0.0'

info:
  title: 'Main Service API'
  version: '1.0.0'
  description: API for signing up, logining in and auth users

servers:
  - url: 'http://localhost:31337'

paths:
  /api/signup:
    post:
      summary: 'Sign up a new user'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
                - login
                - password
      responses:
        '200':
          description: 'User is successfully signed up'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '409':
          description: 'Such user already exists'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        

  /api/login:
    post:
      summary: 'Auth a user'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
                - login
                - password
      responses:
        '200':
          description: 'Successfully logined, token is returned'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  message:
                    type: string

        '403':
          description: 'Invalid login or password'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/update:
    put:
      summary: 'Update user's info'
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                birthdate:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phone:
                  type: string
                bio:
                  type: string
              required:
                - name
                - surname
                - birthdate
                - email
                - phone
                - bio
      responses:
        '200':
          description: 'Successfully updated'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        '403':
          description: 'Auth failed'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT