# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import proto.statistics.protocols_statistics_pb2 as protocols__statistics__pb2


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStatistics = channel.unary_unary(
                '/statistics_service_grpc.StatisticsService/GetPostStatistics',
                request_serializer=protocols__statistics__pb2.PostStatisticsRequest.SerializeToString,
                response_deserializer=protocols__statistics__pb2.PostStatisticsResponse.FromString,
                )
        self.GetTopPosts = channel.unary_unary(
                '/statistics_service_grpc.StatisticsService/GetTopPosts',
                request_serializer=protocols__statistics__pb2.TopPostsRequest.SerializeToString,
                response_deserializer=protocols__statistics__pb2.TopPostsResponse.FromString,
                )
        self.GetTopUsers = channel.unary_unary(
                '/statistics_service_grpc.StatisticsService/GetTopUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=protocols__statistics__pb2.TopUsersResponse.FromString,
                )


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStatistics,
                    request_deserializer=protocols__statistics__pb2.PostStatisticsRequest.FromString,
                    response_serializer=protocols__statistics__pb2.PostStatisticsResponse.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=protocols__statistics__pb2.TopPostsRequest.FromString,
                    response_serializer=protocols__statistics__pb2.TopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=protocols__statistics__pb2.TopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistics_service_grpc.StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics_service_grpc.StatisticsService/GetPostStatistics',
            protocols__statistics__pb2.PostStatisticsRequest.SerializeToString,
            protocols__statistics__pb2.PostStatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics_service_grpc.StatisticsService/GetTopPosts',
            protocols__statistics__pb2.TopPostsRequest.SerializeToString,
            protocols__statistics__pb2.TopPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics_service_grpc.StatisticsService/GetTopUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protocols__statistics__pb2.TopUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
